name: tourist_flutter
description: Tourist Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.7.5
  scoped_model: ^1.0.1
  global_configuration: ^1.5.0
  font_awesome_flutter: ^8.8.1
  logger: ^0.9.2
  shared_preferences: ^0.5.10
  provider: ^4.3.2
  lottie: ^0.6.0
  flushbar: ^1.10.4
  image_picker: ^0.6.7
  carousel_slider: ^2.2.1
  retrofit: ^1.3.4
  chopper: ^3.0.3
  json_annotation: ^3.0.1
  flutter_time_picker_spinner: ^1.0.6+1
  google_maps_flutter: ^0.5.30
  share: ^0.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  build_test: ^1.0.0
  chopper_generator: ^3.0.5
  retrofit_generator: ^1.3.7+2
  json_serializable: ^3.3.0

flutter_icons:
  image_path: "assets/images/icon_app.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/cfg/
